import { Inter } from "next/font/google";
import { League_Spartan, Alegreya  } from 'next/font/google';
import "./globals.css";
import Head from 'next/head';

const leagueSpartan = League_Spartan({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

const alegreya = Alegreya({
  weight: ['400', '700'],
  subsets: ['latin'],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scriptly.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Head>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js" defer></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/vanta/1.0.0/vanta.fog.min.js" defer></script>
        </Head>
        {children}
      </body>
    </html>
  );
}
